// <auto-generated />
using InheritanceStrategyDemoEFCore5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InheritanceStrategyDemoEFCore5.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPCModels.TPCStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CGPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TPCStudents");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPCModels.TPCTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TPCTeachers");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPHModels.TPHUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TPHUsers");

                    b.HasDiscriminator<string>("UserType").HasValue("TPHUser");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TPTUsers");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPHModels.TPHStudent", b =>
                {
                    b.HasBaseType("InheritanceStrategyDemoEFCore5.Models.TPHModels.TPHUser");

                    b.Property<string>("CGPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPHModels.TPHTeacher", b =>
                {
                    b.HasBaseType("InheritanceStrategyDemoEFCore5.Models.TPHModels.TPHUser");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTStudent", b =>
                {
                    b.HasBaseType("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTUser");

                    b.Property<string>("CGPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TPTStudents");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTTeacher", b =>
                {
                    b.HasBaseType("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTUser");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TPTTeachers");
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTStudent", b =>
                {
                    b.HasOne("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTUser", null)
                        .WithOne()
                        .HasForeignKey("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTStudent", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTTeacher", b =>
                {
                    b.HasOne("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTUser", null)
                        .WithOne()
                        .HasForeignKey("InheritanceStrategyDemoEFCore5.Models.TPTModels.TPTTeacher", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
